language: node_js
notifications:
  email: false
node_js:
  - node        # La versión actual más estable
  - lts/*       # La versión actual más estable con soporte a largo plazo
  #- "v15.0.1"   # Se especifica una versión en concreto, la 15.0.1
  #- "12"        # Se especifica una versión, que por defecto sería la versión 12 más actual estable lst 

before_install:
  - npm install grunt-cli
  - docker-compose build

install: grunt install

before_script:
  - docker-compose up -d

script: 
  - grunt test
  # - curl --location --request GET 'http://localhost:${HTTPPORT}/recetas/'
  - wget http://localhost:${HTTP_PORT}/recetas/ || exit 1
  - wget http://localhost:${HTTP_PORT1}/recetas/ || exit 1