version: '3'

services:
  recetas:
    container_name: recetas
    build: 
      context: .
      dockerfile: deploy.Dockerfile
    ports:
         - "3013:3010"

  recetas_aux:
    container_name: recetas_aux
    build: 
      context: .
      dockerfile: deploy.Dockerfile
    ports:
         - "3014:3010"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./log/nginx/:/var/log/nginx/
      
    links:
      - recetas
      - recetas_aux
    ports:
      - "8080:8080"

volumes:
  .: