version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine: true
    steps:
      - checkout
      #Log into registry
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $CIRCLE_USERNAME  --password-stdin
      #Se obtiene la imagen 
      - run: docker pull cr13/recetacoctel

  test:
    machine: true
    steps:
      - checkout
      #Log into registry
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $CIRCLE_USERNAME  --password-stdin
      # Se ejecuta el test
      - run: docker run -t -v `pwd`:/app/test cr13/recetascoctel

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build