version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image:  cr13/recetacoctel:latest
        auth:
          username: $CIRCLE_USERNAME 
          password: $DOCKERHUB_PASSWORD 
    
    steps:
      - checkout
      - run: npm install grunt-cli
      - run: grunt test


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test