version: 1.1

# Define the jobs we want to run for this project
jobs:
  build:
    steps:
      - checkout
      #Log into registry
      run: echo "${{ secrets.MY_GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      #Se construye la imagen 
      run: docker build -t cr13/recetascoctel .

  test:
    steps:
      - checkout
      run: docker run -t -v `pwd`:/app/test cr13/recetascoctel

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build